[package]
name = "neoaudio"
version = "0.1.0"
edition = "2021"

[dependencies]
weresocool_portaudio = "1.0.47"
thiserror = "1.0.61"
crossbeam-channel = "0.5.13"
serde = { version = "1.0", features = ["derive"] }
